language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install mock
#  - pip install 
# command to run tests
script: nosetests
branches:
  only:
    - master
notifications:
  email: false
