language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
os:
  - linux
  - osx
# command to install dependencies
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - build-dep
            - python-numpy
            - python-scipy
      before_install:
        - sudo apt-get build-dep python-scipy
    - os: osx

install:
  - pip install pytest
  - pip install mock
  - pip install -r requirements.txt
# command to run tests
script: python -m pytest
branches:
  only:
    - master
notifications:
  email:
    on_failure: change
    on_succes: never
