language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
before_install:
  - sudo apt-get build-dep python-scipy
  - sudo apt-get install -qq python-numpy python-scipy
install:
  - pip install .[dev]
# command to run tests
script: python -m pytest
branches:
  only:
    - master
notifications:
  email:
    on_failure: change
    on_succes: never
