language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install pytest
  - pip install mock
  - pip install -r requirements.txt
# command to run tests
script: python -m pytest
branches:
  only:
    - master
notifications:
  email:
    on_failure: change
    on_succes: never
