language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo apt-get install -qq opencl-headers
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - pip install mock
  - pip install pyopencl
#  - pip install 
# command to run tests
script: nosetests -v
branches:
  only:
    - master
notifications:
  email: false
